In [1]:
import numpy as np
import pandas as pd

#basic libraries to explore data

In [2]:
game_data=pd.read_csv('../Data/games-data.csv')
game_data.head()

,name,platform,r-date,score,user score,developer,genre,players,critics,users
0,The Legend of Zelda: Ocarina of Time,Nintendo64,"November 23, 1998",99,9.1,Nintendo,"Action Adventure,Fantasy",1 Player,22,5749
1,Tony Hawk's Pro Skater 2,PlayStation,"September 20, 2000",98,7.4,NeversoftEntertainment,"Sports,Alternative,Skateboarding",1-2,19,647
2,Grand Theft Auto IV,PlayStation3,"April 29, 2008",98,7.6,RockstarNorth,"Action Adventure,Modern,Modern,Open-World",1 Player,64,3806
3,SoulCalibur,Dreamcast,"September 8, 1999",98,8.5,Namco,"Action,Fighting,3D",1-2,24,324
4,Grand Theft Auto IV,Xbox360,"April 29, 2008",98,7.9,RockstarNorth,"Action Adventure,Modern,Modern,Open-World",1 Player,86,3364

In [3]:
#changing column names into ones that give better understanding of the data

game_data.rename(columns = {'name' : 'game', 'platform' : 'console', 'r-date' : 'release_date',
                            'score' : 'critic_score', 'user score' : 'user_score',
                            'developer' : 'dev', 'players' : 'player_support','critics' : 'num_critics', 'users' : 'num_users'}, inplace = True )
game_data.head()

,game,console,release_date,critic_score,user_score,dev,genre,player_support,num_critics,num_users
0,The Legend of Zelda: Ocarina of Time,Nintendo64,"November 23, 1998",99,9.1,Nintendo,"Action Adventure,Fantasy",1 Player,22,5749
1,Tony Hawk's Pro Skater 2,PlayStation,"September 20, 2000",98,7.4,NeversoftEntertainment,"Sports,Alternative,Skateboarding",1-2,19,647
2,Grand Theft Auto IV,PlayStation3,"April 29, 2008",98,7.6,RockstarNorth,"Action Adventure,Modern,Modern,Open-World",1 Player,64,3806
3,SoulCalibur,Dreamcast,"September 8, 1999",98,8.5,Namco,"Action,Fighting,3D",1-2,24,324
4,Grand Theft Auto IV,Xbox360,"April 29, 2008",98,7.9,RockstarNorth,"Action Adventure,Modern,Modern,Open-World",1 Player,86,3364

In [4]:
data=game_data.copy()

#working on a copy to make it easier to correct mistakes we make down the line

display(data.head())

,game,console,release_date,critic_score,user_score,dev,genre,player_support,num_critics,num_users
0,The Legend of Zelda: Ocarina of Time,Nintendo64,"November 23, 1998",99,9.1,Nintendo,"Action Adventure,Fantasy",1 Player,22,5749
1,Tony Hawk's Pro Skater 2,PlayStation,"September 20, 2000",98,7.4,NeversoftEntertainment,"Sports,Alternative,Skateboarding",1-2,19,647
2,Grand Theft Auto IV,PlayStation3,"April 29, 2008",98,7.6,RockstarNorth,"Action Adventure,Modern,Modern,Open-World",1 Player,64,3806
3,SoulCalibur,Dreamcast,"September 8, 1999",98,8.5,Namco,"Action,Fighting,3D",1-2,24,324
4,Grand Theft Auto IV,Xbox360,"April 29, 2008",98,7.9,RockstarNorth,"Action Adventure,Modern,Modern,Open-World",1 Player,86,3364

In [5]:
#doing an initial check on both null values and column types

display(data.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 17944 entries, 0 to 17943
Data columns (total 10 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   game            17944 non-null  object
 1   console         17944 non-null  object
 2   release_date    17944 non-null  object
 3   critic_score    17944 non-null  int64
 4   user_score      17944 non-null  object
 5   dev             17944 non-null  object
 6   genre           17944 non-null  object
 7   player_support  17922 non-null  object
 8   num_critics     17944 non-null  int64
 9   num_users       17944 non-null  int64
dtypes: int64(3), object(7)
memory usage: 1.4+ MB

None

In [6]:
display(data['num_users'].value_counts())
display(data['user_score'].unique())
display(data['num_critics'].unique())
display(data['critic_score'].unique())

0       1299
5        490
6        488
7        478
8        449
        ...
1781       1
750        1
671        1
701        1
3970       1
Name: num_users, Length: 1352, dtype: int64

array(['9.1', '7.4', '7.6', '8.5', '7.9', '9.0', '7.8', '8.3', '6.2',
       '8.6', '8.9', '8.4', '9.2', '6.4', '8.2', '8.8', '8.7', '8.0',
       '6.8', '7.5', '6.6', '7.3', '7.1', '8.1', '7.7', '6.5', '9.4',
       '5.7', '5.5', '5.9', '7.2', '6.9', '3.3', '9.3', '5.1', '6.7',
       '3.9', '7.0', '5.4', 'tbd', '6.3', '6.1', '6.0', '5.3', '3.5',
       '5.8', '4.5', '5.0', '4.1', '4.4', '4.9', '3.4', '4.6', '4.3',
       '4.8', '5.6', '1.6', '5.2', '4.2', '4.0', '3.2', '9.7', '3.1',
       '2.8', '4.7', '2.0', '2.3', '3.0', '3.6', '2.6', '1.1', '2.4',
       '2.7', '9.6', '2.9', '2.5', '3.7', '1.7', '2.1', '1.4', '9.8',
       '3.8', '1.3', '1.9', '1.2', '0.5', '1.5', '2.2', '1.8', '0.8',
       '0.4', '0.7', '0.2', '0.6', '0.9'], dtype=object)

array([ 22,  19,  64,  24,  86,  73,  87,  33,  14,  50,  58,  18, 109,
        34,  30,  99,  66,  70,  56, 113,  68,  81,  57,  13,  88,  21,
       105,  82,  54,  42,  15,  98,  16,  89,  38,  80,  44,  62,  85,
         8,  91,  27,  25,  71,  52,  96,  10,  32,  67, 118,  37,  23,
        55,  51,  29,  90,   7,   9,  61,  20,  76,  12,  53, 100,  75,
        72,  36, 121,  74,  17,  43,  48,  83,  35,  77,  41,  46,  69,
        45,  84,  47,  28,  40, 101,  97,  79,  78,  39,  31,  59,  95,
        60,  65,  49,  26,  11,  94, 110,  63,  93,  92, 102, 115, 104,
       126, 107, 111, 116, 106, 122,   6, 114, 103,   0], dtype=int64)

array([99, 98, 97, 96, 95, 94, 93, 92, 91, 90, 89, 88, 87, 86, 85, 84, 83,
       82, 81, 80, 79, 78, 77, 76, 75, 74, 73, 72, 71, 70, 69, 68, 67, 66,
       65, 64, 63, 62, 61, 60, 59, 58, 57, 56, 55, 54, 53, 52, 51, 50, 49,
       48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33, 32,
       31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16, 11],
      dtype=int64)

In [7]:
#Some games have 0 critics or users and there's even a few with no user score,
#so the first thing we need to do is to get rid of those,
#since my main focus is analysing most other columns based on scores.
#For simplicity sake I'm assuming that a review score left by 0 people is fraudulent.

In [8]:
#let's check some rows with either 0 critics or 0 users

display(data[data['num_critics']==0]) 
display(data[data['num_users']==0])

,game,console,release_date,critic_score,user_score,dev,genre,player_support,num_critics,num_users
8422,Yatagarasu: Attack on Cataclysm,PC,"July 7, 2015",73,5.0,No info,"Action,Fighting,2D",No info,0,0
10161,No Man's Land,PC,"October 20, 2003",70,7.1,SelectiveIntuition,"Action,General",No info,0,0
10281,Voodoo Vince Remastered,XboxOne,"April 18, 2017",70,5.9,No info,No info,No info,0,0
10452,Dracula: Origin,PC,"May 23, 2008",70,6.5,BigFishGames,"Adventure,General",No info,0,0
11341,Warlocks vs Shadows,PC,"August 19, 2015",68,tbd,FrozenDistrict,"Role-Playing,Action RPG",Online Multiplayer,0,0
12429,Agatha Christie: The ABC Murders,PC,"February 4, 2016",66,8.5,Kalypso,"Adventure,General,Point-and-Click",No info,0,16
12550,Memento Mori 2,PC,"May 13, 2014",65,7.5,No info,No info,No info,0,0
13056,Shaun Palmer's Pro Snowboarder,PlayStation2,"November 13, 2001",64,8.6,No info,No info,No info,0,0
13439,Pid,PC,"October 31, 2012",63,7.7,JoaoVictordaSilva//LucasRoberto,"Strategy,General",No Online Multiplayer,0,0
13678,Pinball Hall of Fame: The Gottlieb Collection,PlayStation2,"November 16, 2004",63,6.7,No info,No info,No info,0,0
13841,Create,Wii,"November 16, 2010",62,tbd,No info,No info,No info,0,0
13987,Auto Modellista,GameCube,"September 30, 2003",62,tbd,No info,No info,No info,0,0
14005,Madagascar: Escape 2 Africa,Xbox360,"November 4, 2008",62,6.8,No info,No info,No info,0,0
14039,Saint Seiya: Sanctuary Battle,PlayStation3,"March 16, 2012",62,7.6,No info,No info,No info,0,0
14391,StarDrone Extreme,PlayStationVita,"February 22, 2012",61,4.0,No info,No info,No info,0,0
14477,True Crime: New York City,Xbox,"November 15, 2005",60,7.2,No info,No info,No info,0,0
14507,Sega Smash Pack,GameBoyAdvance,"September 23, 2002",60,5.0,No info,No info,No info,0,0
14520,Wario: Master of Disguise,DS,"March 5, 2007",60,7.4,No info,No info,No info,0,0
15590,Naruto Shippuden: Shinobi Rumble,DS,"February 8, 2011",56,tbd,"Eighting,TakaraTomy","Action,General,General,Fighting,2D",No Online Multiplayer,0,0
17107,NightCry,PC,"March 28, 2016",46,3.0,No info,No info,No info,0,0
17373,Painkiller: Redemption,PC,"February 25, 2011",43,5.0,EggtoothTeam,"Action,Shooter,First-Person,Arcade",No info,0,9

,game,console,release_date,critic_score,user_score,dev,genre,player_support,num_critics,num_users
496,Madden NFL 2005,GameCube,"August 9, 2004",90,tbd,EATiburon,"Sports,Traditional,Football,Sim",1-4,26,0
570,Yakuza: Like a Dragon,XboxOne,"November 10, 2020",89,tbd,Sega,"Role-Playing,Japanese-Style",No info,13,0
921,Tiger Woods PGA Tour 2005,GameCube,"September 20, 2004",88,tbd,EASports,"Sports,Traditional,Golf,Sim",1-4,18,0
1216,NASCAR 2005: Chase for the Cup,Xbox,"August 31, 2004",86,tbd,EATiburon,"Driving,Racing,Stock Car",1-2,16,0
1361,Yakuza: Like a Dragon,XboxSeriesX,"November 10, 2020",86,tbd,RyugaGotokuStudios,"Role-Playing,Japanese-Style",No info,10,0
...,...,...,...,...,...,...,...,...,...,...
17750,Jackass the Game,DS,"January 8, 2008",35,tbd,SensorySweep,"Action,General,General",1 Player,10,0
17773,King of Clubs,Wii,"August 4, 2008",35,tbd,OxygenInteractive,"Sports,Traditional,Individual,Golf,Arcade,Arcade",No Online Multiplayer,11,0
17834,Jenga World Tour,DS,"November 13, 2007",32,tbd,AtomicPlanetEntertainment,"Miscellaneous,Puzzle,Party,General",2 Online,7,0
17849,Dream Chronicles,PlayStation3,"November 23, 2010",31,tbd,PlayFirst,"Miscellaneous,Puzzle,Puzzle,Hidden Object,Gene...",No info,8,0
17851,Smash 'N' Survive,PlayStation3,"February 22, 2012",31,tbd,Version2GamesLimited,"Driving,Racing,General,General",No info,16,0

In [9]:
#let's now drop those unwanted rows and check column types

data=data[(data['user_score'] != 'tbd') & (data['num_users'] != 0) & (data['num_critics'] != 0)]
display(data.info())

<class 'pandas.core.frame.DataFrame'>
Int64Index: 16641 entries, 0 to 17943
Data columns (total 10 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   game            16641 non-null  object
 1   console         16641 non-null  object
 2   release_date    16641 non-null  object
 3   critic_score    16641 non-null  int64
 4   user_score      16641 non-null  object
 5   dev             16641 non-null  object
 6   genre           16641 non-null  object
 7   player_support  16619 non-null  object
 8   num_critics     16641 non-null  int64
 9   num_users       16641 non-null  int64
dtypes: int64(3), object(7)
memory usage: 1.4+ MB

None

In [10]:
#checking for null values

data.isnull().sum()

game               0
console            0
release_date       0
critic_score       0
user_score         0
dev                0
genre              0
player_support    22
num_critics        0
num_users          0
dtype: int64

In [11]:
#checking the values of the column with nulls to see if there's an easy fill option

data['player_support'].unique()

array(['1 Player', '1-2 ', 'No Online Multiplayer', 'Up to 32 ',
       'Up to 30 ', 'Up to 16 ', 'No info', '1-4 ', 'Online Multiplayer',
       'Up to 6 ', 'Up to 4 ', '1-16 ', 'Up to 8 ', '2 ', 'Up to 18 ',
       '1-8 ', '8  Online', '2  Online', '4  Online', '1-32 ',
       'Up to 10 ', 'Up to 40 ', 'Massively Multiplayer', 'Up to 12 ',
       'Up to 5 ', nan, '64  Online', 'Up to 20 ', '6  Online',
       '16  Online', '24  Online', '1-6 ', '1-12 ', '64+ ', 'Up to 22 ',
       'Up to 60 ', 'Up to 64 ', '1-10 ', 'Up to 24 ', 'Up to 3 ',
       '12  Online', '10  Online', '32  Online', '1-64 ',
       'Up to more than 64 ', '14  Online', '44  Online', '1-5 ',
       '64+  Online', '1-3 ', '5  Online', 'Up to 14 ', 'Up to 9 ',
       'Up to 36 ', '1-24 ', '3  Online'], dtype=object)

In [12]:
data[data['player_support'].isnull()]

,game,console,release_date,critic_score,user_score,dev,genre,player_support,num_critics,num_users
197,The Sims,PC,"February 4, 2000",92,7.9,Maxis,"Simulation,Miscellaneous,Virtual Life,Virtual,...",NaN,38,665
715,Shenmue II,Dreamcast,"November 23, 2001",88,9.2,SegaAM2,"Action Adventure,Modern",NaN,9,324
994,Thief II: The Metal Age,PC,"March 23, 2000",87,8.9,LookingGlassStudios,"Action Adventure,Fantasy,General,Fantasy",NaN,18,258
1278,Lunar 2: Eternal Blue Complete,PlayStation,"December 15, 2000",86,9.0,GameArts,"Role-Playing,Console-style RPG",NaN,12,57
1373,EverQuest: The Ruins of Kunark,PC,"March 24, 2000",86,8.5,SonyOnlineEntertainment,"Role-Playing,Massively Multiplayer Online,Mass...",NaN,11,31
2172,Ultra Street Fighter IV,Xbox360,"June 3, 2014",84,6.9,Capcom,"Fighting,3D,Action,Fighting,2D,3D",NaN,29,85
2206,Master of Orion II: Battle at Antares,PC,"October 1, 1996",84,8.8,SimTex,"Strategy,Turn-Based,Sci-Fi,4X",NaN,9,37
2298,Ultra Street Fighter IV,PlayStation3,"June 3, 2014",83,7.6,Capcom,"Fighting,3D,Action,Fighting,2D,3D",NaN,28,98
2664,Counter-Strike: Global Offensive,PC,"August 21, 2012",83,7.3,"ValveSoftware,HiddenPathEntertainment","Action,Shooter,Shooter,First-Person,Modern,Tac...",NaN,38,4150
3848,Mutazione,PC,"September 19, 2019",80,7.4,DieGuteFabrik,"Adventure,Point-and-Click",NaN,7,20
4586,Pirates Outlaws,PC,"April 13, 2020",79,7.2,FabledGame,"Strategy,Turn-Based,Card Battle",NaN,9,5
4651,Parasite Eve II,PlayStation,"September 12, 2000",79,8.8,SquareSoft,"Role-Playing,Action RPG",NaN,14,137
5155,Donkey Kong Country,GameBoyAdvance,"June 9, 2003",78,8.8,RareLtd.,"Action,Platformer,2D",NaN,26,72
5402,Earth 2150,PC,"June 12, 2000",78,7.8,TopWareInteractive,"Strategy,Real-Time,Sci-Fi,Sci-Fi,General,Command",NaN,22,48
7881,Fort Triumph,PC,"April 16, 2020",74,7.4,FortTriumphLTD,"General,Strategy,Turn-Based,Tactics",NaN,12,16
8273,Lightmatter,PC,"January 15, 2020",73,7.9,TunnelVisionGames,"Adventure,3D,First-Person",NaN,14,20
8838,Loadout,PC,"May 15, 2013",72,7.3,EdgeofReality,"Shooter,First-Person,Modern,Modern,Action,Shoo...",NaN,17,447
10420,Soulbringer,PC,"June 30, 2000",70,7.8,Infogrames,"Role-Playing,General,General,Action RPG",NaN,19,30
11429,Avencast: Rise of the Mage,PC,"November 8, 2007",68,7.1,ClockStoneSoftware,"Role-Playing,Action RPG,Action RPG",NaN,11,40
13798,Rise of Industry,PC,"May 2, 2019",62,7.6,DapperPenguinStudios,"Government,Strategy,Management,Business / Tycoon",NaN,12,8
13980,FlatOut 4: Total Insanity,PlayStation4,"March 17, 2017",62,6.1,"StrategyFirst,Kylotonn","Racing,Arcade,Automobile",NaN,32,49
16886,Moto Racer 4,PlayStation4,"January 24, 2017",49,4.5,PQube,"Racing,Arcade,Other",NaN,11,13

In [13]:
#it seems that some rows don't have info on the support type, which is a bit annoying but we can use it for the null values

data['player_support'].fillna('No info', inplace=True)
display(data['player_support'].unique())
display(data.isnull().sum())

array(['1 Player', '1-2 ', 'No Online Multiplayer', 'Up to 32 ',
       'Up to 30 ', 'Up to 16 ', 'No info', '1-4 ', 'Online Multiplayer',
       'Up to 6 ', 'Up to 4 ', '1-16 ', 'Up to 8 ', '2 ', 'Up to 18 ',
       '1-8 ', '8  Online', '2  Online', '4  Online', '1-32 ',
       'Up to 10 ', 'Up to 40 ', 'Massively Multiplayer', 'Up to 12 ',
       'Up to 5 ', '64  Online', 'Up to 20 ', '6  Online', '16  Online',
       '24  Online', '1-6 ', '1-12 ', '64+ ', 'Up to 22 ', 'Up to 60 ',
       'Up to 64 ', '1-10 ', 'Up to 24 ', 'Up to 3 ', '12  Online',
       '10  Online', '32  Online', '1-64 ', 'Up to more than 64 ',
       '14  Online', '44  Online', '1-5 ', '64+  Online', '1-3 ',
       '5  Online', 'Up to 14 ', 'Up to 9 ', 'Up to 36 ', '1-24 ',
       '3  Online'], dtype=object)

game              0
console           0
release_date      0
critic_score      0
user_score        0
dev               0
genre             0
player_support    0
num_critics       0
num_users         0
dtype: int64

In [14]:
#Since we no longer have nulls let's go ahead and apply a quick fix to one of our main columns regarding exploration.
#While the critic score comes on a 0-100 scale, the user score is on a 0-10.
#Let's simply multiply the user score by 10 and cast it as an int so we can more easily compare the two score types.

def fix_user_score(x):
    y = float(x) * 10
    return int(y)

data['user_score']=data['user_score'].apply(fix_user_score)
data['user_score'].unique()

array([91, 74, 76, 85, 79, 90, 78, 83, 62, 86, 89, 84, 92, 64, 82, 88, 87,
       80, 68, 75, 66, 73, 71, 81, 77, 65, 94, 57, 55, 59, 72, 69, 33, 93,
       51, 67, 39, 70, 54, 63, 61, 60, 53, 35, 58, 45, 50, 41, 44, 49, 34,
       46, 43, 48, 56, 16, 52, 42, 40, 32, 97, 31, 28, 47, 20, 23, 30, 36,
       26, 11, 24, 27, 96, 29, 25, 37, 17, 21, 14, 98, 38, 13, 19, 12,  5,
       15, 22, 18,  8,  4,  7,  2,  6,  9], dtype=int64)

In [15]:
#Now that both scores are on the same scale, let's add a new column which allows us to compare critic score with user score
#There might be games where the critics liked it, but it didn't actually appeal to the general audiance or vice-versa
#That could be really interesting to explore if there's a console that stands out or even the type of player support
#We'll subtract the critic score FROM the user score
#A positive value indicates users have a better score, and a negative value indicates critics have a better score

data['score_diff']=data['user_score']-data['critic_score']
data.head()

,game,console,release_date,critic_score,user_score,dev,genre,player_support,num_critics,num_users,score_diff
0,The Legend of Zelda: Ocarina of Time,Nintendo64,"November 23, 1998",99,91,Nintendo,"Action Adventure,Fantasy",1 Player,22,5749,-8
1,Tony Hawk's Pro Skater 2,PlayStation,"September 20, 2000",98,74,NeversoftEntertainment,"Sports,Alternative,Skateboarding",1-2,19,647,-24
2,Grand Theft Auto IV,PlayStation3,"April 29, 2008",98,76,RockstarNorth,"Action Adventure,Modern,Modern,Open-World",1 Player,64,3806,-22
3,SoulCalibur,Dreamcast,"September 8, 1999",98,85,Namco,"Action,Fighting,3D",1-2,24,324,-13
4,Grand Theft Auto IV,Xbox360,"April 29, 2008",98,79,RockstarNorth,"Action Adventure,Modern,Modern,Open-World",1 Player,86,3364,-19

In [16]:
#all we have left before we start analysing the categorical columns
#is change the release column to datetime and extracting month and year as integers

data['release_date']= pd.to_datetime(data['release_date'])
data['release_year']=pd.DatetimeIndex(data['release_date']).year
data['release_month']=pd.DatetimeIndex(data['release_date']).month
data.head()

,game,console,release_date,critic_score,user_score,dev,genre,player_support,num_critics,num_users,score_diff,release_year,release_month
0,The Legend of Zelda: Ocarina of Time,Nintendo64,1998-11-23,99,91,Nintendo,"Action Adventure,Fantasy",1 Player,22,5749,-8,1998,11
1,Tony Hawk's Pro Skater 2,PlayStation,2000-09-20,98,74,NeversoftEntertainment,"Sports,Alternative,Skateboarding",1-2,19,647,-24,2000,9
2,Grand Theft Auto IV,PlayStation3,2008-04-29,98,76,RockstarNorth,"Action Adventure,Modern,Modern,Open-World",1 Player,64,3806,-22,2008,4
3,SoulCalibur,Dreamcast,1999-09-08,98,85,Namco,"Action,Fighting,3D",1-2,24,324,-13,1999,9
4,Grand Theft Auto IV,Xbox360,2008-04-29,98,79,RockstarNorth,"Action Adventure,Modern,Modern,Open-World",1 Player,86,3364,-19,2008,4

In [17]:
#let's rearrange the columns a bit

data=data[['game', 'console', 'dev', 'genre', 'player_support', 'critic_score', 'user_score', 'score_diff',
           'num_critics', 'num_users' , 'release_date', 'release_month', 'release_year']]
data.head()

,game,console,dev,genre,player_support,critic_score,user_score,score_diff,num_critics,num_users,release_date,release_month,release_year
0,The Legend of Zelda: Ocarina of Time,Nintendo64,Nintendo,"Action Adventure,Fantasy",1 Player,99,91,-8,22,5749,1998-11-23,11,1998
1,Tony Hawk's Pro Skater 2,PlayStation,NeversoftEntertainment,"Sports,Alternative,Skateboarding",1-2,98,74,-24,19,647,2000-09-20,9,2000
2,Grand Theft Auto IV,PlayStation3,RockstarNorth,"Action Adventure,Modern,Modern,Open-World",1 Player,98,76,-22,64,3806,2008-04-29,4,2008
3,SoulCalibur,Dreamcast,Namco,"Action,Fighting,3D",1-2,98,85,-13,24,324,1999-09-08,9,1999
4,Grand Theft Auto IV,Xbox360,RockstarNorth,"Action Adventure,Modern,Modern,Open-World",1 Player,98,79,-19,86,3364,2008-04-29,4,2008

In [18]:
#Now that we seem to have the initial preparation out of the way
#it's time to go through each categorical column, check the amounth of values
#and, if necessary, combine some values

data.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 16641 entries, 0 to 17943
Data columns (total 13 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   game            16641 non-null  object
 1   console         16641 non-null  object
 2   dev             16641 non-null  object
 3   genre           16641 non-null  object
 4   player_support  16641 non-null  object
 5   critic_score    16641 non-null  int64
 6   user_score      16641 non-null  int64
 7   score_diff      16641 non-null  int64
 8   num_critics     16641 non-null  int64
 9   num_users       16641 non-null  int64
 10  release_date    16641 non-null  datetime64[ns]
 11  release_month   16641 non-null  int64
 12  release_year    16641 non-null  int64
dtypes: datetime64[ns](1), int64(7), object(5)
memory usage: 1.8+ MB

In [19]:
#getting a dataframe with only the columns we want to check
#will use this as the input for the functions without ever changing it
#if my function ever returns me strange things, the original input is still there and i don't need to clear any variables

cat_data=data.select_dtypes(include='object')
cat_data.drop('game', axis=1, inplace=True)
cat_data.head()

,console,dev,genre,player_support
0,Nintendo64,Nintendo,"Action Adventure,Fantasy",1 Player
1,PlayStation,NeversoftEntertainment,"Sports,Alternative,Skateboarding",1-2
2,PlayStation3,RockstarNorth,"Action Adventure,Modern,Modern,Open-World",1 Player
3,Dreamcast,Namco,"Action,Fighting,3D",1-2
4,Xbox360,RockstarNorth,"Action Adventure,Modern,Modern,Open-World",1 Player

In [20]:
for col in cat_data.columns:
    display(cat_data[col].nunique())

20

3968

1981

55

In [21]:
#we definitely need to clean all collumns, but dev and genre especially
#let's start with the smaller ones though

In [22]:
#let's check the unique values for the console column

cat_data['console'].unique()

array(['Nintendo64', 'PlayStation', 'PlayStation3', 'Dreamcast',
       'Xbox360', 'Wii', 'XboxOne', 'Switch', 'PlayStation2',
       'PlayStation4', 'GameCube', 'Xbox', 'PC', 'WiiU', 'GameBoyAdvance',
       '3DS', 'DS', 'PlayStationVita', 'PSP', 'Stadia'], dtype=object)

In [23]:
#if we really want to analyse individual consoles we can't do much,
#but we can create another column if we want to compare the main console producers

def console_groupping(row):
    if "PlayStation" in row or row == "PSP":
        return "PS"
    elif "Xbox" in row:
        return "Xbox"
    elif row == "Dreamcast":
        return "Sega"
    elif row == "Stadia":
        return "Google"
    elif row == "PC":
        return "PC"
    else:
        return "Nintendo"
    
data['console_brand']=cat_data['console'].apply(console_groupping)

In [24]:
display(data['console'].value_counts())
display(data['console_brand'].value_counts())

PC                 4428
PlayStation4       1852
Xbox360            1592
PlayStation2       1300
PlayStation3       1231
XboxOne            1020
Switch             1004
Xbox                658
Wii                 605
DS                  568
PSP                 460
GameCube            411
3DS                 386
GameBoyAdvance      335
PlayStationVita     252
WiiU                185
PlayStation         160
Dreamcast           121
Nintendo64           70
Stadia                3
Name: console, dtype: int64

PS          5255
PC          4428
Nintendo    3564
Xbox        3270
Sega         121
Google         3
Name: console_brand, dtype: int64

In [25]:
#now we can have a much broader plot with the new column or a more narrow one with the old column

#let's move onto cleaning the player_support column

In [26]:
display(cat_data['player_support'].unique())
display(cat_data['player_support'].value_counts())

array(['1 Player', '1-2 ', 'No Online Multiplayer', 'Up to 32 ',
       'Up to 30 ', 'Up to 16 ', 'No info', '1-4 ', 'Online Multiplayer',
       'Up to 6 ', 'Up to 4 ', '1-16 ', 'Up to 8 ', '2 ', 'Up to 18 ',
       '1-8 ', '8  Online', '2  Online', '4  Online', '1-32 ',
       'Up to 10 ', 'Up to 40 ', 'Massively Multiplayer', 'Up to 12 ',
       'Up to 5 ', '64  Online', 'Up to 20 ', '6  Online', '16  Online',
       '24  Online', '1-6 ', '1-12 ', '64+ ', 'Up to 22 ', 'Up to 60 ',
       'Up to 64 ', '1-10 ', 'Up to 24 ', 'Up to 3 ', '12  Online',
       '10  Online', '32  Online', '1-64 ', 'Up to more than 64 ',
       '14  Online', '44  Online', '1-5 ', '64+  Online', '1-3 ',
       '5  Online', 'Up to 14 ', 'Up to 9 ', 'Up to 36 ', '1-24 ',
       '3  Online'], dtype=object)

No Online Multiplayer    4524
No info                  4110
1 Player                 1853
1-2                      1037
1-4                       838
Up to 4                   566
Up to 8                   410
2                         384
Online Multiplayer        366
2  Online                 349
4  Online                 256
1-8                       248
8  Online                 193
Up to 16                  152
Up to 12                  143
Up to 6                   133
Massively Multiplayer     116
Up to 10                  106
16  Online                102
1-16                       82
6  Online                  65
1-6                        55
1-32                       41
32  Online                 40
Up to 22                   36
10  Online                 33
Up to 24                   30
Up to 18                   29
Up to 20                   28
12  Online                 27
Up to 3                    26
Up to 32                   25
1-3                        23
Up to 5                    21
Up to 64                   21
Up to more than 64         20
Up to 40                   20
24  Online                 18
1-5                        17
1-12                       15
1-10                       13
1-64                        8
14  Online                  8
64  Online                  7
5  Online                   7
Up to 14                    7
Up to 30                    5
Up to 60                    5
64+  Online                 5
Up to 9                     5
3  Online                   5
44  Online                  4
64+                         2
Up to 36                    1
1-24                        1
Name: player_support, dtype: int64

In [27]:
cat_data[cat_data['player_support']=='4  Online']

,console,dev,genre,player_support
97,Xbox,UbisoftMontreal,"Action Adventure,Modern",4 Online
191,Xbox360,HarmonixMusicSystems,"Action,Miscellaneous,Rhythm,Music,Music",4 Online
201,Wii,HarmonixMusicSystems,"Action,Miscellaneous,Rhythm,Music,Music",4 Online
244,PlayStation3,HarmonixMusicSystems,"Action,Miscellaneous,Rhythm,Music,Music",4 Online
266,PlayStation3,HarmonixMusicSystems,"Action,Miscellaneous,Rhythm,Music,Music",4 Online
...,...,...,...,...
17534,DS,MileStoneInc.,"Action,Simulation,General,General,Vehicle,Combat",4 Online
17545,Xbox360,FrozenCodebase,"Action,General,General",4 Online
17649,PC,"EnlightSoftware,InfiniteInteractive","Strategy,Real-Time,Historic,Historic,Command",4 Online
17703,Xbox360,"Voltex,Inc.","Action,General,General",4 Online
17836,PSP,LeftFieldProductions,"Driving,Racing,Arcade,Other,Other",4 Online

In [28]:
#we have way too many values here, but we'll try to simplify them into 4 (counting "no info"):
#singleplayer, co-op, and multiplayer
#the biggest problem, is where to draw the line
#any games with online could be counted as multiplayer, howevere there are online co-op games
#a game with up to 4 players could either be an online co-op or a regular multiplayer
#to keep it simple, even if it might not be 100% exact, i'll aggregate any games with a maximum of 4 players into co-op

In [29]:
def fix_player_count(row):
    if row == "No info":
        return "No info"
    elif row == "1 Player" or row == "No Online Multiplayer":
        return "Singleplayer"
    elif row=="1-2 " or row=="1-3 " or row=="1-4 " or row=="2 " or row=="Up to 3 " or row=="Up to 4 " or row=="2  Online"  or row=="3  Online"  or row=="4  Online" :
        return "Co-op"
    else:
        return "Multiplayer"

In [30]:
data['player_support']=cat_data['player_support'].apply(fix_player_count)
display(data['player_support'].value_counts())

Singleplayer    6377
No info         4110
Co-op           3484
Multiplayer     2670
Name: player_support, dtype: int64

In [31]:
#looks way nicer now
#let's move onto the first nightmare: genre

In [32]:
cat_data['genre'].unique()

array(['Action Adventure,Fantasy', 'Sports,Alternative,Skateboarding',
       'Action Adventure,Modern,Modern,Open-World', ...,
       'Massively Multiplayer Online,Modern,Role-Playing,Massively Multiplayer',
       'Driving,Action Adventure,Modern,Racing,General,Modern,Motorcycle,Motocross',
       'Driving,Modern,Racing,Motorcycle,Motocross,Modern,Action Adventure,General'],
      dtype=object)

In [33]:
#from the looks of it, most games have multiple genres, which makes sense
#however we don't want to have a massive plot with every single genre combination
#so my initial idea is to get the main genre, and potentially a secondary genre for the games that have it

In [34]:
def genre_cleaning(row):
    g=row.split(",")
    return g[0]

data['main_genre']=cat_data['genre'].apply(genre_cleaning)
print(data['main_genre'].nunique())
display(data['main_genre'].value_counts().head(15))

62

Action              5629
Action Adventure    2148
Role-Playing        1676
Sports              1409
Strategy            1359
Miscellaneous       1025
Adventure            981
Driving              849
Simulation           515
Racing               245
General              224
Puzzle               142
Sci-Fi                63
Fantasy               60
Modern                45
Name: main_genre, dtype: int64

In [35]:
#still ended up with 60+ genres, so let's group the least represented ones into "Other"

data['main_genre']= np.where(data['main_genre'].isin(['Action', 'Action Adventure', 'Role-Playing', 'Sports', 'Strategy', 'Miscellaneous', 'Adventure', 'Driving', 'Simulation']) , data['main_genre'], 'Other')
data['main_genre'].value_counts()

Action              5629
Action Adventure    2148
Role-Playing        1676
Sports              1409
Strategy            1359
Other               1050
Miscellaneous       1025
Adventure            981
Driving              849
Simulation           515
Name: main_genre, dtype: int64